from django.urls import path, include # Django functions for defining URL patterns

# DRF component for automatically generating the URL conf for a set of views.
from rest_framework.routers import DefaultRouter

# Views for handling JWT authentication
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# For handling task-related operations
from .views import TaskViewSet

# Creates an instance of `DefaultRouter`, which will automatically generate the
# URL patterns for the viewsets registered with it
router = DefaultRouter

# Registers the `TaskViewSet` with the router. This creates the necessary URL patterns
# for the CRUD operations on the `Task` model. The `basename` is used to generate the
# URL names.
router.register(r'tasks', TaskViewSet, basename='task')

urlpatterns = [
    # Includes the URL patterns generated by the router under the /api/ prefix
    path('api/', include(router.urls)),

    # Defines the endpoint for obtaining a JWT token pair (access and refresh tokens.)
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),

    # Defines the endpoint for refreshing an access token using a refresh token
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]